#!/bin/bash
function load {
cd ~/ProfitTrailer
cp application.properties application.properties.backup
cp configuration.properties configuration.properties.backup
cp trading/PAIRS.properties trading/PAIRS.properties.backup
cp trading/INDICATORS.properties trading/INDICATORS.properties.backup
cp trading/DCA.properties trading/DCA.properties.backup
cp ~/app.prop/application.properties.$PROFILE application.properties
curl https://raw.githubusercontent.com/tomohern/PTS/$PROFILE/configuration.properties > configuration.properties
curl https://raw.githubusercontent.com/tomohern/PTS/$PROFILE/INDICATORS.properties > trading/INDICATORS.properties
curl https://raw.githubusercontent.com/tomohern/PTS/$PROFILE/PAIRS.properties > trading/PAIRS.properties
curl https://raw.githubusercontent.com/tomohern/PTS/$PROFILE/DCA.properties > trading/DCA.properties
echo $PROFILE loaded.
}
function unload {
cd ~/ProfitTrailer
cp application.properties.backup application.properties
cp configuration.properties.backup configuration.properties
cp trading/PAIRS.properties.backup trading/PAIRS.properties
cp trading/INDICATORS.properties.backup trading/INDICATORS.properties
cp trading/DCA.properties.backup trading/DCA.properties
echo Backups restored
}
curl https://raw.githubusercontent.com/tomohern/PTS/master/profiles > ~/profiles.txt
VALUES=$(<~/profiles.txt)
OPTIONS="$VALUES Restore Quit"
select opt in $OPTIONS; do
   if [ "$opt" = "Quit" ]; then
    echo done
    exit
   elif [ "$opt" = "BTFD" ]; then
    PROFILE=BTFD
    load
   elif [ "$opt" = "ccbull" ]; then
    PROFILE=ccbull
    load
   elif [ "$opt" = "ccbear" ]; then
    PROFILE=ccbear
    load
   elif [ "$opt" = "Restore" ]; then
    unload
   else
    clear
    echo bad option
   fi
done
