#!/bin/bash
echo Enter Desired Username:
read uname
adduser $uname
usermod -aG sudo $uname
apt update
apt install openjdk-8-jre-headless
apt install unzip
curl https://raw.githubusercontent.com/tomohern/PTS/scripts/profittrailer > /usr/local/bin/profittrailer
chmod +x /usr/local/bin/profittrailer
curl https://raw.githubusercontent.com/tomohern/PTS/scripts/loadprofile > /usr/local/bin/loadprofile
chmod +x /usr/local/bin/loadprofile
curl https://raw.githubusercontent.com/tomohern/PTS/scripts/setup2 > /usr/local/bin/setup2
chmod +x /usr/local/bin/setup2
echo Please execute 'setup2'
su - $uname
