#!/bin/bash
echo Enter Desired Username:
read uname
adduser $uname
usermod -aG sudo $uname
apt update
apt install openjdk-8-jre-headless
apt install unzip
curl https://raw.githubusercontent.com/tomohern/PTS/scripts/profittrailer > /usr/local/bin/profittrailer
chmod +x /usr/local/bin/profittrailer
curl https://raw.githubusercontent.com/tomohern/PTS/scripts/loadprofile > /usr/local/bin/loadprofile
chmod +x /usr/local/bin/loadprofile
#curl $(curl -s https://api.github.com/repos/taniman/profit-trailer/releases/latest | grep 'browser_' | cut -d\" -f4) > /home/$uname/ProfitTrailer.zip
ver=$(curl -s https://api.github.com/repos/taniman/profit-trailer/releases/latest | grep 'browser_' | cut -d '/' -f8)
runuser -l  $uname -c 'curl https://github.com/taniman/profit-trailer/releases/download/$ver/ProfitTrailer.zip  > /home/$uname/ProfitTrailer.zip'
runuser -l  $uname -c 'unzip /home/$uname/ProfitTrailer.zip'
runuser -l  $uname -c 'mv ProfitTrailer.zip ProfitTrailer_$ver.zip'
runuser -l  $uname -c 'mkdir /home/$uname/app.prop'
runuser -l  $uname -c 'cp /home/$uname/ProfitTrailer/application.properties /home/$uname/app.prop/application.properties.DEFAULT'
su - $uname
